/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPuskesmas;


import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;

;
/**
 *
 * @author mufli
 */
public final class Pendaftaran extends javax.swing.JFrame {
    
    
    private void kosongkan_form(){
        
        nikTextBox.setText(null);
        namaTextBox.setText(null);
        umurTextBox.setText(null);
        alamatTextBox.setText(null);
        JenisKelamincb.setSelectedItem(null);
        noTelpTextBox.setText(null);
        hariComboBox.setSelectedItem(null);
        tanggalComboBox.setSelectedItem(null);
        waktuComboBox.setSelectedItem(null);
        bulanComboBox.setSelectedItem(null);
        poliComboBox.setSelectedItem(null);
        keluhanTextBox.setText(null);
    }
    private void tampilkan_data(){
        DefaultTableModel tabel_pasien = new DefaultTableModel();
        tabel_pasien.addColumn("No");
        tabel_pasien.addColumn("NIK");
        tabel_pasien.addColumn("Nama");
        tabel_pasien.addColumn("Umur");
        tabel_pasien.addColumn("Alamat");
        tabel_pasien.addColumn("Jenis Kelamin");
        tabel_pasien.addColumn("No Telp");
        tabel_pasien.addColumn("Hari");
        tabel_pasien.addColumn("Tanggal");
        tabel_pasien.addColumn("Bulan");
        tabel_pasien.addColumn("Waktu");
        tabel_pasien.addColumn("Poli");
        tabel_pasien.addColumn("Keluhan");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pasien_puskesmas";
            Connection conn = Konfig.configDB();
            Statement state = conn.createStatement();
            ResultSet res = state.executeQuery(sql);
            
            while(res.next()){
                tabel_pasien.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),
                    res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12)});
            }
            
            tabelPasien.setModel(tabel_pasien);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "gagal");
        }
        
    }
    
    /**
     * Creates new form Pendaftaran
     */
    public Pendaftaran() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        Umur = new javax.swing.JLabel();
        noTelp = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        keluarButton = new javax.swing.JButton();
        daftarButton = new javax.swing.JButton();
        JenisKelamincb = new javax.swing.JComboBox<>();
        NIK = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        noTelpTextBox = new javax.swing.JTextField();
        alamatTextBox = new javax.swing.JTextField();
        umurTextBox = new javax.swing.JTextField();
        namaTextBox = new javax.swing.JTextField();
        nikTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        poliComboBox = new javax.swing.JComboBox<>();
        keluhanTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hariComboBox = new javax.swing.JComboBox<>();
        waktuComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tanggalComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bulanComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        BatalButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPasien = new javax.swing.JTable();
        hapusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("tabel pasien"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ISI DATA PASIEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, 21));

        jenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenisKelamin.setText("Jenis Kelamin :");
        getContentPane().add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 96, 21));

        Umur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Umur.setText("Umur :");
        getContentPane().add(Umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 96, 21));

        noTelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noTelp.setText("No Telp :");
        getContentPane().add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 96, 21));

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat.setText("Alamat :");
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 96, 21));

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(keluarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, -1, -1));

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(daftarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 440, -1, -1));

        JenisKelamincb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki Laki", "Perempuan" }));
        JenisKelamincb.setToolTipText("");
        JenisKelamincb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKelamincbActionPerformed(evt);
            }
        });
        getContentPane().add(JenisKelamincb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 100, 25));

        NIK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NIK.setText("NIK:");
        getContentPane().add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 96, 21));

        Nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nama.setText("Nama :");
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 96, 21));

        noTelpTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(noTelpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 300, 25));

        alamatTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(alamatTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 300, 25));

        umurTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(umurTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 300, 25));

        namaTextBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(namaTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 300, 25));

        nikTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(nikTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 300, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KELUHAN PASIEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, 21));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Keluhan :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 76, 21));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Waktu :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 100, 21));

        poliComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poli Anak", "Poli Gigi", "Poli Umum", "Poli Covid" }));
        poliComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(poliComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 100, 25));

        keluhanTextBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keluhanTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluhanTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(keluhanTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 300, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Poli :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 76, 21));

        hariComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin ", "Selasa", "Rabu", "Kamis", "Jumat" }));
        getContentPane().add(hariComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 100, 25));

        waktuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam 9 AM", "Jam 10 AM", "Jam 11 AM", "Jam 13 PM", "Jam 14 PM" }));
        getContentPane().add(waktuComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 100, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bulan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 100, 21));

        tanggalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tanggalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tanggalComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 230, 100, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 100, 21));

        bulanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(bulanComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 270, 100, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PUSKESMAS SEHAT ABADI");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 460, 40));

        BatalButton.setText("Batal");
        BatalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BatalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, 70, -1));

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 440, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Hari :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 100, 21));

        tabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPasien.setRowHeight(20);
        tabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1480, 290));

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 70, -1));

        setSize(new java.awt.Dimension(1514, 1037));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // buat exit
        
        int questionExit = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar?","Keluar dari Aplikasi",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(questionExit == JOptionPane.OK_OPTION){
            System.exit(0);
            
            if(questionExit == JOptionPane.CANCEL_OPTION){
                
            }
        }
    
    }//GEN-LAST:event_keluarButtonActionPerformed
    
    
   
    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed

        // masukin data ke database
        try{
            
            String sql = "INSERT INTO `pasien_puskesmas`(`nikPasien`, `namaPasien`, `umurPasien`, `alamatPasien`, `jenisKelamin`, `noTelp`, `hari`, `tanggal`, `waktu`,`bulan`, `poli`, `keluhan`) "
                    + "VALUES ('"+nikTextBox.getText()+"','"+namaTextBox.getText()+"','"+umurTextBox.getText()+"','"+alamatTextBox.getText()+"','"+JenisKelamincb.getSelectedItem()+"','"+noTelpTextBox.getText()+"',"
                    + "'"+hariComboBox.getSelectedItem()+"','"+tanggalComboBox.getSelectedItem()+"','"+waktuComboBox.getSelectedItem()+"','"+bulanComboBox.getSelectedItem()+"','"+poliComboBox.getSelectedItem()+"','"+keluhanTextBox.getText()+"')";
            
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement state = conn.prepareStatement(sql);
            state.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Mendaftar");
            tampilkan_data();
            kosongkan_form();
            
        
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
            
       
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void JenisKelamincbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKelamincbActionPerformed
        // memilih jenis kelamin
      
    }//GEN-LAST:event_JenisKelamincbActionPerformed

    private void noTelpTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpTextBoxActionPerformed

    private void alamatTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTextBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alamatTextBoxActionPerformed

    private void umurTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurTextBoxActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_umurTextBoxActionPerformed

    private void namaTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_namaTextBoxActionPerformed

    private void nikTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextBoxActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nikTextBoxActionPerformed

    private void poliComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliComboBoxActionPerformed

    }//GEN-LAST:event_poliComboBoxActionPerformed

    private void keluhanTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluhanTextBoxActionPerformed
        
    }//GEN-LAST:event_keluhanTextBoxActionPerformed

    private void tanggalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalComboBoxActionPerformed
        
    }//GEN-LAST:event_tanggalComboBoxActionPerformed

    private void BatalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalButtonActionPerformed
        
        kosongkan_form();
        
    }//GEN-LAST:event_BatalButtonActionPerformed

    private void tabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienMouseClicked
        
        int baris = tabelPasien.rowAtPoint(evt.getPoint());
        String nik = tabelPasien.getValueAt(baris, 1).toString();
        nikTextBox.setText(nik);
        String nama = tabelPasien.getValueAt(baris, 2).toString();
        namaTextBox.setText(nama);
        String umur = tabelPasien.getValueAt(baris, 3).toString();
        umurTextBox.setText(umur);
        String alamat = tabelPasien.getValueAt(baris, 4).toString();
        alamatTextBox.setText(alamat);
        String jenis_kelamin = tabelPasien.getValueAt(baris, 5).toString();
        JenisKelamincb.setSelectedItem(jenis_kelamin);
        String no_telpon = tabelPasien.getValueAt(baris, 6).toString();
        noTelpTextBox.setText(no_telpon);
        String hari = tabelPasien.getValueAt(baris, 7).toString();
        hariComboBox.setSelectedItem(hari);
        String tanggal = tabelPasien.getValueAt(baris, 8).toString();
        tanggalComboBox.setSelectedItem(tanggal);
        String bulan = tabelPasien.getValueAt(baris, 9).toString();
        bulanComboBox.setSelectedItem(bulan);
        String waktu = tabelPasien.getValueAt(baris, 10).toString();
        waktuComboBox.setSelectedItem(waktu);
        String poli = tabelPasien.getValueAt(baris, 11).toString();
        poliComboBox.setSelectedItem(poli);
        String keluhan = tabelPasien.getValueAt(baris, 12).toString();
        keluhanTextBox.setText(keluhan);
        
        
    }//GEN-LAST:event_tabelPasienMouseClicked

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        
        
        try{
            String sql = "UPDATE `pasien_puskesmas` SET `nikPasien`='"+nikTextBox.getText()+"',`namaPasien`='"+namaTextBox.getText()+"',`umurPasien`='"+umurTextBox.getText()+"',`alamatPasien`='"+alamatTextBox.getText()+"',`jenisKelamin`='"+JenisKelamincb.getSelectedItem()+"',`noTelp`='"+noTelpTextBox.getText()+"',"
                    + "`hari`='"+hariComboBox.getSelectedItem()+"',`tanggal`='"+tanggalComboBox.getSelectedItem()+"',`bulan`='"+bulanComboBox.getSelectedItem()+"',`waktu`='"+waktuComboBox.getSelectedItem()+"',`poli`='"+poliComboBox.getSelectedItem()+"',`keluhan`='"+keluhanTextBox.getText()+"' WHERE nikPasien='"+nikTextBox.getText()+"'";
                    Connection conn = Konfig.configDB();
                    PreparedStatement state = conn.prepareStatement(sql);
                    state.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil Update Data");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form(); 
        
        
    }//GEN-LAST:event_EditButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        
        int delete = tabelPasien.getSelectedRow();
        
        tabelPasien.getValueAt(delete, 1);
        
        int question = JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Data?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection conn = Konfig.configDB();
                String sql = "DELETE FROM `pasien_puskesmas` WHERE nikPasien = '"+nikTextBox.getText()+"'";
                PreparedStatement deleteData = conn.prepareStatement(sql);
                
                deleteData.execute();
                
                JOptionPane.showMessageDialog(null, "Data Terhapus");
            }catch(SQLException e){
                System.out.println("Terjadi Kesalahan");
            }
            tampilkan_data();
            kosongkan_form();
            
            
            if(question == JOptionPane.CANCEL_OPTION){
                
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pendaftaran().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JButton BatalButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JComboBox<String> JenisKelamincb;
    private javax.swing.JLabel NIK;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Umur;
    private javax.swing.JTextField alamatTextBox;
    private javax.swing.JComboBox<String> bulanComboBox;
    private javax.swing.JButton daftarButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JComboBox<String> hariComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField keluhanTextBox;
    public javax.swing.JTextField namaTextBox;
    private javax.swing.JTextField nikTextBox;
    private javax.swing.JLabel noTelp;
    private javax.swing.JTextField noTelpTextBox;
    private javax.swing.JComboBox<String> poliComboBox;
    private javax.swing.JTable tabelPasien;
    private javax.swing.JComboBox<String> tanggalComboBox;
    private javax.swing.JTextField umurTextBox;
    private javax.swing.JComboBox<String> waktuComboBox;
    // End of variables declaration//GEN-END:variables
}
